Test fix path names 2

diff --git a/.github/workflows/MacPushBuildWithExisting.yml b/.github/workflows/MacPushBuildWithExisting.yml
--- a/.github/workflows/MacPushBuildWithExisting.yml
+++ b/.github/workflows/MacPushBuildWithExisting.yml
@@ -19,6 +19,103 @@ jobs:
           done < mainConfig.txt
         shell: bash
 
+      - name: Get SkedaiSatRunner using version number
+        id: download-skedaisatrunner
+        run: |
+          skedaisatrunner_version=${{ env.skedaisatrunner_version }}
+          skedaisatrunner_version_lower=$(echo "$skedaisatrunner_version" | tr '[:upper:]' '[:lower:]')
+
+          if [ "$skedaisatrunner_version_lower" == "latest" ]; then
+            echo "Fetching the latest release..."
+            response=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiSatRunner/releases/latest")
+          else
+            echo "Fetching release for version $skedaisatrunner_version..."
+            response=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiSatRunner/releases/tags/$skedaisatrunner_version")
+          fi
+
+          http_status=$(echo "$response" | tail -n1)
+          json_response=$(echo "$response" | sed '$d')
+          echo "HTTP Status: $http_status"
+
+          if [ "$http_status" != "200" ]; then
+            echo "Release not found, looking for artifact"
+            artifacts_response=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiSatRunner/actions/artifacts")
+            artifacts_http_status=$(echo "$artifacts_response" | tail -n1)
+            artifacts_json=$(echo "$artifacts_response" | sed '$d')
+            echo "Artifacts HTTP Status: $artifacts_http_status"
+
+            if [ "$artifacts_http_status" == "200" ]; then
+              matchingArtifacts=$(echo "$artifacts_json" | jq -r --arg version "_mac$skedaisatrunner_version" --arg version2 "_mac_$skedaisatrunner_version" '.artifacts[] | select(.name | endswith($version) or endswith($version2)) | .id' | head -n 1)
+              if [ -z "$matchingArtifacts" ]; then
+                echo "No matching artifact found for version $skedaisatrunner_version"
+                exit 1
+              fi
+              download_url="https://api.github.com/repos/proshkin/SkedaiSatRunner/actions/artifacts/$matchingArtifacts/zip"
+              echo "Download URL: $download_url"
+              curl -L -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" -o artifact.zip "$download_url"
+              artifactDir="components"
+              mkdir -p $artifactDir
+              unzip -q artifact.zip -d $artifactDir
+
+              exePattern1="skedaiSatRunner_mac"
+              exePattern2="SkedaiSatRunner"
+              exeFile=$(find $artifactDir -name "$exePattern1" -o -name "$exePattern2" | head -n 1)
+              if [ -n "$exeFile" ]; then
+                mv "$exeFile" "$artifactDir/skedaiSatRunner_mac"
+              else
+                echo "No executable file matching the pattern '$exePattern1' or '$exePattern2' found in the extracted artifacts."
+                echo "Files found in artifact directory:"
+                find $artifactDir -type f
+                exit 1
+              fi
+            else
+              echo "Failed to fetch artifacts. HTTP Status: $artifacts_http_status"
+              exit 1
+            fi
+          else
+            echo "Release found. Checking assets..."
+            download_url=$(echo "$json_response" | jq -r --arg version "mac_$skedaisatrunner_version" '.assets[] | select(.name | endswith($version)).browser_download_url')
+            if [ -z "$download_url" ]; then
+              echo "No macOS asset found in the release. Looking for artifact instead."
+              artifacts_response=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiSatRunner/actions/artifacts")
+              artifacts_http_status=$(echo "$artifacts_response" | tail -n1)
+              artifacts_json=$(echo "$artifacts_response" | sed '$d')
+              echo "Artifacts HTTP Status: $artifacts_http_status"
+
+              if [ "$artifacts_http_status" == "200" ]; then
+                matchingArtifacts=$(echo "$artifacts_json" | jq -r --arg version "_mac$skedaisatrunner_version" --arg version2 "_mac_$skedaisatrunner_version" '.artifacts[] | select(.name | endswith($version) or endswith($version2)) | .id' | head -n 1)
+                if [ -z "$matchingArtifacts" ]; then
+                  echo "No matching artifact found for version $skedaisatrunner_version"
+                  exit 1
+                fi
+                download_url="https://api.github.com/repos/proshkin/SkedaiSatRunner/actions/artifacts/$matchingArtifacts/zip"
+                echo "Download URL: $download_url"
+                curl -L -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" -o artifact.zip "$download_url"
+                artifactDir="components"
+                mkdir -p $artifactDir
+                unzip -q artifact.zip -d $artifactDir
+
+                exePattern1="skedaiSatRunner_mac"
+                exePattern2="SkedaiSatRunner"
+                exeFile=$(find $artifactDir -name "$exePattern1" -o -name "$exePattern2" | head -n 1)
+                if [ -n "$exeFile" ]; then
+                  mv "$exeFile" "$artifactDir/skedaiSatRunner_mac"
+                else
+                  echo "No executable file matching the pattern '$exePattern1' or '$exePattern2' found in the extracted artifacts."
+                  echo "Files found in artifact directory:"
+                  find $artifactDir -type f
+                  exit 1
+                fi
+              else
+                echo "Failed to fetch artifacts. HTTP Status: $artifacts_http_status"
+                exit 1
+              fi
+            else
+              echo "Download URL: $download_url"
+              curl -L -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" -o components/skedaiSatRunner_mac "$download_url"
+            fi
+          fi
+        shell: bash
 
       - name: Get Authenticator using version number
         id: download-authenticator
@@ -119,7 +216,6 @@ jobs:
         shell: bash
 
 
-
       - name: Get UserServer using version number
         id: download-userserver
         run: |
@@ -144,9 +240,9 @@ jobs:
             artifacts_http_status=$(echo "$artifacts_response" | tail -n1)
             artifacts_json=$(echo "$artifacts_response" | sed '$d')
             echo "Artifacts HTTP Status: $artifacts_http_status"
-            
+
             if [ "$artifacts_http_status" == "200" ]; then
-              matchingArtifacts=$(echo "$artifacts_json" | jq -r --arg version "_mac$userserver_version" '.artifacts[] | select(.name | endswith($version) or endswith("_" + $version)) | .id' | head -n 1)
+              matchingArtifacts=$(echo "$artifacts_json" | jq -r --arg version "_mac$userserver_version" --arg version2 "_mac_$userserver_version" '.artifacts[] | select(.name | endswith($version) or endswith($version2)) | .id' | head -n 1)
               if [ -z "$matchingArtifacts" ]; then
                 echo "No matching artifact found for version $userserver_version"
                 exit 1
@@ -158,12 +254,15 @@ jobs:
               mkdir -p $artifactDir
               unzip -q artifact.zip -d $artifactDir
 
-              exePattern="userServer_mac"
-              exeFile=$(find $artifactDir -name "$exePattern" | head -n 1)
+              exePattern1="userServer_mac"
+              exePattern2="userServer"
+              exeFile=$(find $artifactDir -name "$exePattern1" -o -name "$exePattern2" | head -n 1)
               if [ -n "$exeFile" ]; then
                 mv "$exeFile" "$artifactDir/userServer_mac"
               else
-                echo "No executable file matching the pattern '$exePattern' found in the extracted artifacts."
+                echo "No executable file matching the pattern '$exePattern1' or '$exePattern2' found in the extracted artifacts."
+                echo "Files found in artifact directory:"
+                find $artifactDir -type f
                 exit 1
               fi
             else
@@ -172,16 +271,16 @@ jobs:
             fi
           else
             echo "Release found. Checking assets..."
-            download_url=$(echo "$json_response" | jq -r --arg version "mac_${userserver_version}" '.assets[] | select(.name | endswith($version)).browser_download_url')
+            download_url=$(echo "$json_response" | jq -r --arg version "mac_$userserver_version" '.assets[] | select(.name | endswith($version)).browser_download_url')
             if [ -z "$download_url" ]; then
               echo "No macOS asset found in the release. Looking for artifact instead."
               artifacts_response=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiUserServer/actions/artifacts")
               artifacts_http_status=$(echo "$artifacts_response" | tail -n1)
               artifacts_json=$(echo "$artifacts_response" | sed '$d')
               echo "Artifacts HTTP Status: $artifacts_http_status"
-              
+
               if [ "$artifacts_http_status" == "200" ]; then
-                matchingArtifacts=$(echo "$artifacts_json" | jq -r --arg version "_mac$userserver_version" '.artifacts[] | select(.name | endswith($version) or endswith("_" + $version)) | .id' | head -n 1)
+                matchingArtifacts=$(echo "$artifacts_json" | jq -r --arg version "_mac$userserver_version" --arg version2 "_mac_$userserver_version" '.artifacts[] | select(.name | endswith($version) or endswith($version2)) | .id' | head -n 1)
                 if [ -z "$matchingArtifacts" ]; then
                   echo "No matching artifact found for version $userserver_version"
                   exit 1
@@ -193,12 +292,15 @@ jobs:
                 mkdir -p $artifactDir
                 unzip -q artifact.zip -d $artifactDir
 
-                exePattern="userServer_mac"
-                exeFile=$(find $artifactDir -name "$exePattern" | head -n 1)
+                exePattern1="userServer_mac"
+                exePattern2="userServer"
+                exeFile=$(find $artifactDir -name "$exePattern1" -o -name "$exePattern2" | head -n 1)
                 if [ -n "$exeFile" ]; then
                   mv "$exeFile" "$artifactDir/userServer_mac"
                 else
-                  echo "No executable file matching the pattern '$exePattern' found in the extracted artifacts."
+                  echo "No executable file matching the pattern '$exePattern1' or '$exePattern2' found in the extracted artifacts."
+                  echo "Files found in artifact directory:"
+                  find $artifactDir -type f
                   exit 1
                 fi
               else
